name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies  
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run tests
      - name: Run test
        run: python --version